### ISSUE TITLE
Создать в БД таблицу, которая будет содержать события

### ISSUE THREAD

**Issue by AndreyPomelov** [AndreyPomelov/Telegram-bot#11]
Создать в БД таблицу, которая соответствует Entity-классу, описывающему событие, получаемое с портала. Структура таблицы должна соответствовать данному Entity-классу. Написать flyway-скрипт для накатывания данных изменений в БД.

**Comment by ondimon** [comment]
Не понятно зачем тебе БД, когда ты должен обращаться по API к сервису мероприятий и тянуть от туда. У себя ты ничего не должен хранить
